### PR TITLE
Update Phala Network logo and team information.

### PR DESCRIPTION
**Pull request by HashWarlock**
Request to make changes to Phala Network information and logo to reflect current status of the project.

### CODE REVIEW

**Review by SBalaguer — CHANGES_REQUESTED** [review]
Thanks @HashWarlock for the PR! However, a couple things to note:
1. 'WASM' is not a type supported by our Front End, so please remove it.
2. 'Infrastructure' category is for teams that are building infrastructure across chains, think about Wallets, Indexers, etc. It would not apply to Phala, please leave it as 'Smart Contracts'.
3. 'Tag' should be kept to 'Chain' as, again, "Cloud and Off-Chain Computation" is not a tag supported by our Front End.

**Comment by HashWarlock** [comment]
@SBalaguer Thank you for the feedback. I'll make appropriate changes. On the second point:
> 'Infrastructure' category is for teams that are building infrastructure across chains, think about Wallets, Indexers, etc. It would not apply to Phala, please leave it as 'Smart Contracts'.
One of our key distinctions for our Phat Contracts are that they are not Smart Contracts. This is due to them running in our secure enclave off-chain workers and with access to the Internet through HTTPS requests w/ near 0 latency via Queries. Some of the functionality we can provide include:
- Derive sr25519, ed25519 & ecdsa Key pairs to handle attestation services
- Send Calls to RPC nodes w/ HTTPS requests
- Oracle Services
- Bots (i.e Discord/Telegram)
- Middleware service to connect to Storage services like AWS S3, Arweave, IPFS
- Secret File Storage
- Data stream processing for IoT

Another Dapp we provide is SubBridge which is an XCM Router + ChainBridge for token transfers from EVM chains like ETH to Khala parachain & route to parachains we have an HRMP channel open with. This is where we feel that our project lies under the Infrastructure services or requires a new category like "Cloud and Off-Chain Computation" as "Smart Contracts" tends to relate to On-Chain computation which is limited when it comes to scaling computation & latency. What are your thoughts?

**Comment by HashWarlock** [comment]
Updates based on feedback. Let me know if any other items need to be addressed.

**Review by SBalaguer — APPROVED** [review]
Thanks for the changes!

**Review by rmnprkrl — CHANGES_REQUESTED** [review]
@HashWarlock do you happen to have the logo in better quality or SVG?

**Comment by HashWarlock** [comment]
> @HashWarlock do you happen to have the logo in better quality or SVG?

Added a better quality SVG.

**Pull request merged**
