### PR TITLE
Add midnight + crop image

### PR DESCRIPTION
**Pull request by mordamax**
Original PR: https://github.com/paritytech/substrate-website/pull/348

### CODE REVIEW

**Comment by mordamax** [comment]
@rickymidnight cropped the image here 
https://deploy-preview-349--substrate-website.netlify.app/ecosystem/projects/midnightnetwork/

image
image

**Review by rzadp — APPROVED** [review]

**Comment by rickymidnight** [comment]
Hi,

I sent through 3 commits last month, but I don't see the branch for the
project page updated yet.

Is there something I may have missed?

Thanks,
Ricky

Github username: rickymidnight

**Comment by mordamax** [comment]
@rickymidnight sorry, I've asked you to check the cropped image, and forgot to followup after no response. 
I just merged and it has been deployed https://substrate.io/ecosystem/projects/midnightnetwork/

**Comment by rickymidnight** [comment]
No problem, I'm glad we've been able to resolve it.

The only feedback I've received from the team already is a change to the
description. Could I kindly ask you to remove, *("Midnight") *from the text
below. Everything else is great.

The Midnight network (“Midnight”) exists to remove the barriers preventing
organizations and service providers from leveraging blockchain technology
while offering programmable data protection with selective disclosure.

**Pull request merged**
