### PR TITLE
Add a mobile announcement banner about Polkadot SDK

### PR DESCRIPTION
**Pull request by rzadp**
- Addresses [this](https://github.com/polkadot-developers/substrate-docs/pull/2172#issuecomment-2315642856).

[Here](https://github.com/paritytech/substrate-website-banner/pull/11), we added an announcement banner about Polkadot SDK to the website. However it only shows up on **desktop** resolutions.

This introduces the same information as a form of a top announcement banner, visible on **mobile** resolutions.

- [x] This needs [this PR to be merged first](https://github.com/paritytech/gatsby-plugin-substrate/pull/10).

https://github.com/user-attachments/assets/0a532e7c-3afd-4587-be80-466010047a2a

### CODE REVIEW

**Comment by rzadp** [comment]
For some reason the feature does not show on the Netlify deply preview, I don't know why.
Could be something with caching dependencies?

It shows up locally.

**Comment by mordamax** [comment]
> For some reason the feature does not show on the Netlify deply preview, I don't know why. Could be something with caching dependencies?
> 
> It shows up locally.

did you try to build locally with production mode?

i can see it in sources though, but not in the content of the pages layout

image

**Comment by rzadp** [comment]
> did you try to build locally with production mode?

I did, same result.

It looks like it doesn't use updated version of git submodule `gatsby-plugin-substrate`

**Comment by rzadp** [comment]
It worked now after this: https://github.com/paritytech/substrate-website/pull/350/commits/516d26cd5486409e6a1a8d4dccca8a67ccca5065

It was also mentioned [here](https://github.com/paritytech/gatsby-plugin-substrate?tab=readme-ov-file#troubleshooting).

**Comment by rzadp** [comment]
After triggering the cache invalidation, it appears now.

@mordamax Can you review it now?

Not sure it makes sense to dig deeper into this cache problem, since the website is being decommissioned.

**Review by mordamax — APPROVED** [review]

**Pull request merged**
