### PR TITLE
Adding Midnight network as a new project 

### PR DESCRIPTION
**Pull request by rickymidnight**
Adding Midnight network as a new project.

### CODE REVIEW

**Review by gilescope — APPROVED** [review]
Looks reasonable. I can confirm the information is accurate.

**Comment by mordamax** [comment]
@rickymidnight there was some temp glitch on netlify so it all failed, but i've manually rebuilt it:
https://deploy-preview-348--substrate-website.netlify.app/ecosystem/projects/midnightnetwork/

Let me know if that looks ok. Otherwise you can push updates and it will most likely rebuild normally.

**Comment by rickymidnight** [comment]
Thanks for the notification. I need to change the logo as it is not
rendering correctly, otherwise everything else looks good.

Can you describe how I can change the logo please?

And can you confirm the CLA has been signed?

**Comment by mordamax** [comment]
> Thanks for the notification. I need to change the logo as it is not rendering correctly, otherwise everything else looks good. Can you describe how I can change the logo please? 

You need to upload more square-ish one, like https://github.com/paritytech/substrate-website/blob/c5353fc6d9edd9563eae204f272c41fecdb40faa/media/images/projects/acurast.png or see other images
The one you uploaded is too wide rectangle so it's not rendered properly
image


> And can you confirm the CLA has been signed?

Google Chrome 2024-08-09 11 41 54

Looks like signed

**Comment by rickymidnight** [comment]
Thank you. Do I need to wait for the pull request to be approved, to make
the change? Or alternatively could you please upload the logo on my behalf?
This is my first experience of adding a project to substrate, so I'm still
finding my way around and having some difficulty.

**Comment by mordamax** [comment]
@rickymidnight will close this one in favour of https://github.com/paritytech/substrate-website/pull/349

**Pull request closed without merging**
